import prisma from "@/lib/prisma";
import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { Metadata } from "next";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const blog = await prisma.blog.findUnique({ where: { slug } });
  if (!blog || !blog.isPublished) return { title: "Blog Not Found" };

  return {
    title: blog.title,
    description: "Read the latest from Invoq.",
  };
}

export default async function BlogViewPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const blog = await prisma.blog.findUnique({ where: { slug } });

  if (!blog || !blog.isPublished) {
    notFound();
  }

  return (
    <div className="min-h-screen bg-slate-50 py-16 px-6 lg:px-8">
      <div className="max-w-3xl mx-auto">
        <Link href="/blogs" className="inline-flex items-center gap-2 text-slate-500 hover:text-slate-900 mb-8 transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back to Blogs
        </Link>
        
        <article className="bg-white rounded-2xl shadow-sm border border-slate-100 p-8 sm:p-12">
          {/* We use dangerouslySetInnerHTML safely here since content is internally generated by SuperAdmin */}
          <div 
            className="prose prose-slate prose-lg max-w-none prose-headings:text-slate-900 prose-p:text-slate-700 prose-img:rounded-xl"
            dangerouslySetInnerHTML={{ __html: blog.htmlContent }} 
          />
        </article>
      </div>
    </div>
  );
}
